bootstrap.servers=kafka:29092

# Converters
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

# Offset
offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000
offset.storage.topic=gw-offset

# Producer tuning
producer.batch.size=512000
producer.linger.ms=20

# Plugin path
plugin.path=/kafka-connect/jars