name=mongo-source-connector
connector.class=com.mongodb.kafka.connect.MongoSourceConnector
tasks.max=1

# MongoDB connection
connection.uri=mongodb://mongos:27017/
database=gwfinn_db_local
collection=sample

# Startup mode — only new changes, no history
startup.mode=latest

# Full document
publish.full.document.only=false
change.stream.full.document=updateLookup
change.stream.full.document.before.change=whenAvailable

# Batch & poll
batch.size=1000
poll.max.batch.size=1000
poll.await.time.ms=2000

# Offset
offset.partition.name=gw.1

# Pipeline — watch specific collections
# Add all collections you want to watch
pipeline=[{"$match": {"ns.coll": {"$in": ["sample", "collection2", "collection3"]}}}]

# Heartbeat
heartbeat.interval.ms=30000
heartbeat.topic.name=gw-heartbeat-topic

# Topic mapping
topic.mapper=com.mongodb.kafka.connect.source.topic.mapping.DefaultTopicMapper
topic.prefix=mongo

# Output format
output.format.value=json
output.format.key=json
output.json.formatter=com.mongodb.kafka.connect.source.json.formatter.SimplifiedJson

# Error handling
errors.tolerance=all
errors.log.enable=true
errors.log.include.messages=true